### ISSUE TITLE
CRITICAL: AttributeError: module 'pelican-toc' has no attribute 'register'

### ISSUE THREAD

**Issue by floatovh** [ovh/docs-developer-env#7]
Hello,

Right after followed README instructions to build and launch the docker image, the site is empty and I got the following logs :

```
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.5.10
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `ovh_entities`
DEBUG: Registering plugin `ovh_entities`
DEBUG: Loading plugin `ovh_filters`
DEBUG: Registering plugin `ovh_filters`
DEBUG: Loading plugin `ovh_markdown`
DEBUG: Registering plugin `ovh_markdown`
DEBUG: Loading plugin `pelican-toc`
DEBUG: Registering plugin `pelican-toc`
CRITICAL: AttributeError: module 'pelican-toc' has no attribute 'register'
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 393, in main
    pelican, settings = get_instance(args)
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 382, in get_instance
    return cls(settings), settings
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 53, in __init__
    self.init_plugins()
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 80, in init_plugins
    plugin.register()
AttributeError: module 'pelican-toc' has no attribute 'register'
```

**Comment by kimung** [comment]
Hello,

[docs-rendering](https://github.com/ovh/docs-rendering) seems a better fitting for this issue.
`docs-developer-env` is just a wrapper around it

**Comment by floatovh** [comment]
Hello @kimung,

You're right, thanks, I'm closing this one to create it in the good project.
